name: inventory_management_system
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_analytics: ^11.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  firebase_crashlytics: ^4.0.2
  app_settings: ^5.1.1
  google_fonts: ^6.2.1
  country_picker: ^2.0.26
  slide_popup_dialog_null_safety: ^1.0.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  animated_splash_screen: ^1.3.0
  material_dialogs: ^1.1.4
  modal_bottom_sheet: ^3.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  file_picker: ^8.0.6
  uuid: ^3.0.7
  dio: ^5.5.0+1
  cached_network_image: ^3.3.1
  flutter_cached_pdfview: ^0.4.2
  path_provider: ^2.1.3
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  provider: ^6.1.2
  just_audio: ^0.9.39
  share_plus: ^9.0.0
  google_mobile_ads: ^5.1.0
  video_player: ^2.9.1
  quickalert: ^1.1.0
  skeletonizer: ^1.3.0
  tiktoklikescroller: ^0.2.6
  agora_uikit: ^1.3.10
  http: ^1.2.1
  agora_rtc_engine: ^6.3.2
  badges: ^3.1.2
  flutter_animated_dialog: ^2.0.1
  skeletons: ^0.0.3
  file_selector: ^1.0.3
  file_selector_windows: ^0.9.3+1
  
  file_selector_platform_interface: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/icons/
     - assets/logo/
     - assets/audio/
